"""Added uuid column

Revision ID: 5f34fa27ab3d
Revises: 978e6769798e
Create Date: 2023-10-02 23:16:12.808645

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f34fa27ab3d'
down_revision = '978e6769798e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activation_UUID', sa.UUID(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('activation_UUID')

    # ### end Alembic commands ###
