"""Inital commit. Created users and sites tables

Revision ID: de6b3d5564d2
Revises: 
Create Date: 2023-09-18 13:44:36.449224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'de6b3d5564d2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sites',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('sect1title', sa.Text(), nullable=True),
    sa.Column('sect1text', sa.Text(), nullable=True),
    sa.Column('sect2itle', sa.Text(), nullable=True),
    sa.Column('sect2text', sa.Text(), nullable=True),
    sa.Column('sect3itle', sa.Text(), nullable=True),
    sa.Column('sect3text', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sites')
    op.drop_table('users')
    # ### end Alembic commands ###
